# This is a basic workflow to help you get started with Actions

name: Nightly Compliance Check

# Controls when the action will run. 
on:
  # Trigger every day
  schedule:
    - cron: "13 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install refget-compliance

      - name: Run Refget reference
        run: "refget-compliance report --server https://refget.herokuapp.com/ --no-web --json_path _data/refget-server-perl.json"

#       - name: Run Refget reference
#         run: |
#           echo -n '<h1>' > index.html 
#           date +%s >> index.html
#           echo '</h1>' >> index.html

      - name: Commit report
        run: |
          git config --global user.name 'Automated Commit'
          git config --global user.email 'automated@users.noreply.github.com'
          git commit -am "Automated report"
          git push

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
